services:
  traefik:
    tty: true
    image: traefik:v3.5
    container_name: traefik-go
    restart: unless-stopped
    ports:
      - "80:80"
      - "8000:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/traefik.yaml:/etc/traefik/traefik.yml # Mount the config file
    networks:
      - symbol-service-network

  symbol-service:
    image: symbol-service:latest
    build:
      context: ./symbol-service
      dockerfile: Dockerfile
      args:
        - TARGETARCH=arm64
        - TARGETOS=linux
    container_name: symbol-service
    networks:
      - symbol-service-network
    volumes:
      - ./symbol-service/configs:/data/conf
    depends_on:
      mysql:
        condition: service_healthy
    command: [ "./symbol-service", "--conf", "/data/conf/config.docker.yaml" ]
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.symbols.rule=Host(`symbols.localhost`)"
      - "traefik.http.routers.symbols.entrypoints=web"
      - "traefik.http.routers.symbols.middlewares=clean-headers"
      - "traefik.http.services.symbols.loadbalancer.server.port=8000"
      - "traefik.http.middlewares.clean-headers.headers.customresponseheaders.Cache-Control=no-cache"
    environment:
      - CONFIG_PATH=/data/conf
      - GOMAXPROCS=12

  symbol-migration:
    image: symbol-service:latest
    volumes:
      - ./symbol-service/bin:/app
      - ./symbol-service/configs:/data/conf
    networks:
      - symbol-service-network
    depends_on:
      mysql:
        condition: service_healthy
    command: [ "./migrate", "--conf", "/data/conf/config.docker.yaml" ]
    environment:
      - CONFIG_PATH=/data/conf

  mysql:
    image: mysql:8.0
    container_name: symbol-service-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - symbol-service-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 5s
      retries: 5
      interval: 10s


volumes:
  mysql_data:

networks:
  symbol-service-network:
