// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.12.4
// source: symbol/v1/symbols.proto

package v1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Ordering options
type ListSymbolsRequest_OrderBy int32

const (
	ListSymbolsRequest_ORDER_BY_UNSPECIFIED ListSymbolsRequest_OrderBy = 0
	ListSymbolsRequest_ORDER_BY_ID          ListSymbolsRequest_OrderBy = 1
	ListSymbolsRequest_ORDER_BY_LABEL       ListSymbolsRequest_OrderBy = 3
)

// Enum value maps for ListSymbolsRequest_OrderBy.
var (
	ListSymbolsRequest_OrderBy_name = map[int32]string{
		0: "ORDER_BY_UNSPECIFIED",
		1: "ORDER_BY_ID",
		3: "ORDER_BY_LABEL",
	}
	ListSymbolsRequest_OrderBy_value = map[string]int32{
		"ORDER_BY_UNSPECIFIED": 0,
		"ORDER_BY_ID":          1,
		"ORDER_BY_LABEL":       3,
	}
)

func (x ListSymbolsRequest_OrderBy) Enum() *ListSymbolsRequest_OrderBy {
	p := new(ListSymbolsRequest_OrderBy)
	*p = x
	return p
}

func (x ListSymbolsRequest_OrderBy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ListSymbolsRequest_OrderBy) Descriptor() protoreflect.EnumDescriptor {
	return file_symbol_v1_symbols_proto_enumTypes[0].Descriptor()
}

func (ListSymbolsRequest_OrderBy) Type() protoreflect.EnumType {
	return &file_symbol_v1_symbols_proto_enumTypes[0]
}

func (x ListSymbolsRequest_OrderBy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ListSymbolsRequest_OrderBy.Descriptor instead.
func (ListSymbolsRequest_OrderBy) EnumDescriptor() ([]byte, []int) {
	return file_symbol_v1_symbols_proto_rawDescGZIP(), []int{9, 0}
}

type ListSymbolsRequest_SortDirection int32

const (
	ListSymbolsRequest_SORT_DIRECTION_UNSPECIFIED ListSymbolsRequest_SortDirection = 0
	ListSymbolsRequest_SORT_DIRECTION_ASC         ListSymbolsRequest_SortDirection = 1
	ListSymbolsRequest_SORT_DIRECTION_DESC        ListSymbolsRequest_SortDirection = 2
)

// Enum value maps for ListSymbolsRequest_SortDirection.
var (
	ListSymbolsRequest_SortDirection_name = map[int32]string{
		0: "SORT_DIRECTION_UNSPECIFIED",
		1: "SORT_DIRECTION_ASC",
		2: "SORT_DIRECTION_DESC",
	}
	ListSymbolsRequest_SortDirection_value = map[string]int32{
		"SORT_DIRECTION_UNSPECIFIED": 0,
		"SORT_DIRECTION_ASC":         1,
		"SORT_DIRECTION_DESC":        2,
	}
)

func (x ListSymbolsRequest_SortDirection) Enum() *ListSymbolsRequest_SortDirection {
	p := new(ListSymbolsRequest_SortDirection)
	*p = x
	return p
}

func (x ListSymbolsRequest_SortDirection) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ListSymbolsRequest_SortDirection) Descriptor() protoreflect.EnumDescriptor {
	return file_symbol_v1_symbols_proto_enumTypes[1].Descriptor()
}

func (ListSymbolsRequest_SortDirection) Type() protoreflect.EnumType {
	return &file_symbol_v1_symbols_proto_enumTypes[1]
}

func (x ListSymbolsRequest_SortDirection) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ListSymbolsRequest_SortDirection.Descriptor instead.
func (ListSymbolsRequest_SortDirection) EnumDescriptor() ([]byte, []int) {
	return file_symbol_v1_symbols_proto_rawDescGZIP(), []int{9, 1}
}

type Symbol struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ProjectId       int32                  `protobuf:"varint,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Uid             string                 `protobuf:"bytes,3,opt,name=uid,proto3" json:"uid,omitempty"`
	Label           string                 `protobuf:"bytes,4,opt,name=label,proto3" json:"label,omitempty"`
	ClassName       string                 `protobuf:"bytes,5,opt,name=class_name,json=className,proto3" json:"class_name,omitempty"`
	ComponentTarget string                 `protobuf:"bytes,6,opt,name=component_target,json=componentTarget,proto3" json:"component_target,omitempty"`
	Version         string                 `protobuf:"bytes,7,opt,name=version,proto3" json:"version,omitempty"`
	Data            []byte                 `protobuf:"bytes,8,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Symbol) Reset() {
	*x = Symbol{}
	mi := &file_symbol_v1_symbols_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Symbol) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Symbol) ProtoMessage() {}

func (x *Symbol) ProtoReflect() protoreflect.Message {
	mi := &file_symbol_v1_symbols_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Symbol.ProtoReflect.Descriptor instead.
func (*Symbol) Descriptor() ([]byte, []int) {
	return file_symbol_v1_symbols_proto_rawDescGZIP(), []int{0}
}

func (x *Symbol) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Symbol) GetProjectId() int32 {
	if x != nil {
		return x.ProjectId
	}
	return 0
}

func (x *Symbol) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *Symbol) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *Symbol) GetClassName() string {
	if x != nil {
		return x.ClassName
	}
	return ""
}

func (x *Symbol) GetComponentTarget() string {
	if x != nil {
		return x.ComponentTarget
	}
	return ""
}

func (x *Symbol) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Symbol) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// CREATE
type CreateSymbolRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProjectId       int32                  `protobuf:"varint,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Uid             string                 `protobuf:"bytes,3,opt,name=uid,proto3" json:"uid,omitempty"`
	Label           string                 `protobuf:"bytes,4,opt,name=label,proto3" json:"label,omitempty"`
	ClassName       string                 `protobuf:"bytes,5,opt,name=class_name,json=className,proto3" json:"class_name,omitempty"`
	ComponentTarget string                 `protobuf:"bytes,6,opt,name=component_target,json=componentTarget,proto3" json:"component_target,omitempty"`
	Version         string                 `protobuf:"bytes,7,opt,name=version,proto3" json:"version,omitempty"`
	Data            []byte                 `protobuf:"bytes,8,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateSymbolRequest) Reset() {
	*x = CreateSymbolRequest{}
	mi := &file_symbol_v1_symbols_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSymbolRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSymbolRequest) ProtoMessage() {}

func (x *CreateSymbolRequest) ProtoReflect() protoreflect.Message {
	mi := &file_symbol_v1_symbols_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSymbolRequest.ProtoReflect.Descriptor instead.
func (*CreateSymbolRequest) Descriptor() ([]byte, []int) {
	return file_symbol_v1_symbols_proto_rawDescGZIP(), []int{1}
}

func (x *CreateSymbolRequest) GetProjectId() int32 {
	if x != nil {
		return x.ProjectId
	}
	return 0
}

func (x *CreateSymbolRequest) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *CreateSymbolRequest) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *CreateSymbolRequest) GetClassName() string {
	if x != nil {
		return x.ClassName
	}
	return ""
}

func (x *CreateSymbolRequest) GetComponentTarget() string {
	if x != nil {
		return x.ComponentTarget
	}
	return ""
}

func (x *CreateSymbolRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *CreateSymbolRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type CreateSymbolResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        *Symbol                `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSymbolResponse) Reset() {
	*x = CreateSymbolResponse{}
	mi := &file_symbol_v1_symbols_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSymbolResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSymbolResponse) ProtoMessage() {}

func (x *CreateSymbolResponse) ProtoReflect() protoreflect.Message {
	mi := &file_symbol_v1_symbols_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSymbolResponse.ProtoReflect.Descriptor instead.
func (*CreateSymbolResponse) Descriptor() ([]byte, []int) {
	return file_symbol_v1_symbols_proto_rawDescGZIP(), []int{2}
}

func (x *CreateSymbolResponse) GetSymbol() *Symbol {
	if x != nil {
		return x.Symbol
	}
	return nil
}

// UPDATE
type UpdateSymbolRequest struct {
	state           protoimpl.MessageState  `protogen:"open.v1"`
	Id              int32                   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ProjectId       *wrapperspb.Int32Value  `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Uid             *wrapperspb.StringValue `protobuf:"bytes,3,opt,name=uid,proto3" json:"uid,omitempty"`
	Label           *wrapperspb.StringValue `protobuf:"bytes,4,opt,name=label,proto3" json:"label,omitempty"`
	ClassName       *wrapperspb.StringValue `protobuf:"bytes,5,opt,name=class_name,json=className,proto3" json:"class_name,omitempty"`
	ComponentTarget *wrapperspb.StringValue `protobuf:"bytes,6,opt,name=component_target,json=componentTarget,proto3" json:"component_target,omitempty"`
	Version         *wrapperspb.StringValue `protobuf:"bytes,7,opt,name=version,proto3" json:"version,omitempty"`
	Data            *wrapperspb.BytesValue  `protobuf:"bytes,8,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateSymbolRequest) Reset() {
	*x = UpdateSymbolRequest{}
	mi := &file_symbol_v1_symbols_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSymbolRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSymbolRequest) ProtoMessage() {}

func (x *UpdateSymbolRequest) ProtoReflect() protoreflect.Message {
	mi := &file_symbol_v1_symbols_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSymbolRequest.ProtoReflect.Descriptor instead.
func (*UpdateSymbolRequest) Descriptor() ([]byte, []int) {
	return file_symbol_v1_symbols_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateSymbolRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateSymbolRequest) GetProjectId() *wrapperspb.Int32Value {
	if x != nil {
		return x.ProjectId
	}
	return nil
}

func (x *UpdateSymbolRequest) GetUid() *wrapperspb.StringValue {
	if x != nil {
		return x.Uid
	}
	return nil
}

func (x *UpdateSymbolRequest) GetLabel() *wrapperspb.StringValue {
	if x != nil {
		return x.Label
	}
	return nil
}

func (x *UpdateSymbolRequest) GetClassName() *wrapperspb.StringValue {
	if x != nil {
		return x.ClassName
	}
	return nil
}

func (x *UpdateSymbolRequest) GetComponentTarget() *wrapperspb.StringValue {
	if x != nil {
		return x.ComponentTarget
	}
	return nil
}

func (x *UpdateSymbolRequest) GetVersion() *wrapperspb.StringValue {
	if x != nil {
		return x.Version
	}
	return nil
}

func (x *UpdateSymbolRequest) GetData() *wrapperspb.BytesValue {
	if x != nil {
		return x.Data
	}
	return nil
}

type UpdateSymbolResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        *Symbol                `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSymbolResponse) Reset() {
	*x = UpdateSymbolResponse{}
	mi := &file_symbol_v1_symbols_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSymbolResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSymbolResponse) ProtoMessage() {}

func (x *UpdateSymbolResponse) ProtoReflect() protoreflect.Message {
	mi := &file_symbol_v1_symbols_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSymbolResponse.ProtoReflect.Descriptor instead.
func (*UpdateSymbolResponse) Descriptor() ([]byte, []int) {
	return file_symbol_v1_symbols_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateSymbolResponse) GetSymbol() *Symbol {
	if x != nil {
		return x.Symbol
	}
	return nil
}

// DELETE
type DeleteSymbolRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSymbolRequest) Reset() {
	*x = DeleteSymbolRequest{}
	mi := &file_symbol_v1_symbols_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSymbolRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSymbolRequest) ProtoMessage() {}

func (x *DeleteSymbolRequest) ProtoReflect() protoreflect.Message {
	mi := &file_symbol_v1_symbols_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSymbolRequest.ProtoReflect.Descriptor instead.
func (*DeleteSymbolRequest) Descriptor() ([]byte, []int) {
	return file_symbol_v1_symbols_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteSymbolRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteSymbolResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSymbolResponse) Reset() {
	*x = DeleteSymbolResponse{}
	mi := &file_symbol_v1_symbols_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSymbolResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSymbolResponse) ProtoMessage() {}

func (x *DeleteSymbolResponse) ProtoReflect() protoreflect.Message {
	mi := &file_symbol_v1_symbols_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSymbolResponse.ProtoReflect.Descriptor instead.
func (*DeleteSymbolResponse) Descriptor() ([]byte, []int) {
	return file_symbol_v1_symbols_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteSymbolResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// READ
type GetSymbolRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSymbolRequest) Reset() {
	*x = GetSymbolRequest{}
	mi := &file_symbol_v1_symbols_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSymbolRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSymbolRequest) ProtoMessage() {}

func (x *GetSymbolRequest) ProtoReflect() protoreflect.Message {
	mi := &file_symbol_v1_symbols_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSymbolRequest.ProtoReflect.Descriptor instead.
func (*GetSymbolRequest) Descriptor() ([]byte, []int) {
	return file_symbol_v1_symbols_proto_rawDescGZIP(), []int{7}
}

func (x *GetSymbolRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetSymbolResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        *Symbol                `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSymbolResponse) Reset() {
	*x = GetSymbolResponse{}
	mi := &file_symbol_v1_symbols_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSymbolResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSymbolResponse) ProtoMessage() {}

func (x *GetSymbolResponse) ProtoReflect() protoreflect.Message {
	mi := &file_symbol_v1_symbols_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSymbolResponse.ProtoReflect.Descriptor instead.
func (*GetSymbolResponse) Descriptor() ([]byte, []int) {
	return file_symbol_v1_symbols_proto_rawDescGZIP(), []int{8}
}

func (x *GetSymbolResponse) GetSymbol() *Symbol {
	if x != nil {
		return x.Symbol
	}
	return nil
}

// LIST
type ListSymbolsRequest struct {
	state         protoimpl.MessageState           `protogen:"open.v1"`
	ProjectId     int32                            `protobuf:"varint,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	PageSize      int32                            `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                           `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	OrderBy       ListSymbolsRequest_OrderBy       `protobuf:"varint,4,opt,name=order_by,json=orderBy,proto3,enum=symbols.v1.ListSymbolsRequest_OrderBy" json:"order_by,omitempty"`
	SortDirection ListSymbolsRequest_SortDirection `protobuf:"varint,5,opt,name=sort_direction,json=sortDirection,proto3,enum=symbols.v1.ListSymbolsRequest_SortDirection" json:"sort_direction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSymbolsRequest) Reset() {
	*x = ListSymbolsRequest{}
	mi := &file_symbol_v1_symbols_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSymbolsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSymbolsRequest) ProtoMessage() {}

func (x *ListSymbolsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_symbol_v1_symbols_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSymbolsRequest.ProtoReflect.Descriptor instead.
func (*ListSymbolsRequest) Descriptor() ([]byte, []int) {
	return file_symbol_v1_symbols_proto_rawDescGZIP(), []int{9}
}

func (x *ListSymbolsRequest) GetProjectId() int32 {
	if x != nil {
		return x.ProjectId
	}
	return 0
}

func (x *ListSymbolsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListSymbolsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListSymbolsRequest) GetOrderBy() ListSymbolsRequest_OrderBy {
	if x != nil {
		return x.OrderBy
	}
	return ListSymbolsRequest_ORDER_BY_UNSPECIFIED
}

func (x *ListSymbolsRequest) GetSortDirection() ListSymbolsRequest_SortDirection {
	if x != nil {
		return x.SortDirection
	}
	return ListSymbolsRequest_SORT_DIRECTION_UNSPECIFIED
}

type ListSymbolsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbols       []*Symbol              `protobuf:"bytes,1,rep,name=symbols,proto3" json:"symbols,omitempty"`
	PageToken     string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	NextPage      int32                  `protobuf:"varint,3,opt,name=next_page,json=nextPage,proto3" json:"next_page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSymbolsResponse) Reset() {
	*x = ListSymbolsResponse{}
	mi := &file_symbol_v1_symbols_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSymbolsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSymbolsResponse) ProtoMessage() {}

func (x *ListSymbolsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_symbol_v1_symbols_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSymbolsResponse.ProtoReflect.Descriptor instead.
func (*ListSymbolsResponse) Descriptor() ([]byte, []int) {
	return file_symbol_v1_symbols_proto_rawDescGZIP(), []int{10}
}

func (x *ListSymbolsResponse) GetSymbols() []*Symbol {
	if x != nil {
		return x.Symbols
	}
	return nil
}

func (x *ListSymbolsResponse) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListSymbolsResponse) GetNextPage() int32 {
	if x != nil {
		return x.NextPage
	}
	return 0
}

var File_symbol_v1_symbols_proto protoreflect.FileDescriptor

const file_symbol_v1_symbols_proto_rawDesc = "" +
	"\n" +
	"\x17symbol/v1/symbols.proto\x12\n" +
	"symbols.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x17validate/validate.proto\"\x9f\x02\n" +
	"\x06Symbol\x12\x17\n" +
	"\x02id\x18\x01 \x01(\x05B\a\xfaB\x04\x1a\x02 \x00R\x02id\x12&\n" +
	"\n" +
	"project_id\x18\x02 \x01(\x05B\a\xfaB\x04\x1a\x02 \x00R\tprojectId\x12\x19\n" +
	"\x03uid\x18\x03 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x03uid\x12\x1d\n" +
	"\x05label\x18\x04 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x05label\x12&\n" +
	"\n" +
	"class_name\x18\x05 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\tclassName\x122\n" +
	"\x10component_target\x18\x06 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x0fcomponentTarget\x12!\n" +
	"\aversion\x18\a \x01(\tB\a\xfaB\x04r\x02\x10\x01R\aversion\x12\x1b\n" +
	"\x04data\x18\b \x01(\fB\a\xfaB\x04z\x02\x10\x01R\x04data\"\x93\x02\n" +
	"\x13CreateSymbolRequest\x12&\n" +
	"\n" +
	"project_id\x18\x02 \x01(\x05B\a\xfaB\x04\x1a\x02 \x00R\tprojectId\x12\x19\n" +
	"\x03uid\x18\x03 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x03uid\x12\x1d\n" +
	"\x05label\x18\x04 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x05label\x12&\n" +
	"\n" +
	"class_name\x18\x05 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\tclassName\x122\n" +
	"\x10component_target\x18\x06 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x0fcomponentTarget\x12!\n" +
	"\aversion\x18\a \x01(\tB\a\xfaB\x04\x1a\x02 \x00R\aversion\x12\x1b\n" +
	"\x04data\x18\b \x01(\fB\a\xfaB\x04z\x02\x10\x01R\x04data\"L\n" +
	"\x14CreateSymbolResponse\x124\n" +
	"\x06symbol\x18\x01 \x01(\v2\x12.symbols.v1.SymbolB\b\xfaB\x05\x8a\x01\x02\x10\x01R\x06symbol\"\xbd\x03\n" +
	"\x13UpdateSymbolRequest\x12\x17\n" +
	"\x02id\x18\x01 \x01(\x05B\a\xfaB\x04\x1a\x02 \x00R\x02id\x12:\n" +
	"\n" +
	"project_id\x18\x02 \x01(\v2\x1b.google.protobuf.Int32ValueR\tprojectId\x12.\n" +
	"\x03uid\x18\x03 \x01(\v2\x1c.google.protobuf.StringValueR\x03uid\x122\n" +
	"\x05label\x18\x04 \x01(\v2\x1c.google.protobuf.StringValueR\x05label\x12;\n" +
	"\n" +
	"class_name\x18\x05 \x01(\v2\x1c.google.protobuf.StringValueR\tclassName\x12G\n" +
	"\x10component_target\x18\x06 \x01(\v2\x1c.google.protobuf.StringValueR\x0fcomponentTarget\x126\n" +
	"\aversion\x18\a \x01(\v2\x1c.google.protobuf.StringValueR\aversion\x12/\n" +
	"\x04data\x18\b \x01(\v2\x1b.google.protobuf.BytesValueR\x04data\"L\n" +
	"\x14UpdateSymbolResponse\x124\n" +
	"\x06symbol\x18\x01 \x01(\v2\x12.symbols.v1.SymbolB\b\xfaB\x05\x8a\x01\x02\x10\x01R\x06symbol\"%\n" +
	"\x13DeleteSymbolRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"0\n" +
	"\x14DeleteSymbolResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"+\n" +
	"\x10GetSymbolRequest\x12\x17\n" +
	"\x02id\x18\x01 \x01(\x05B\a\xfaB\x04\x1a\x02 \x00R\x02id\"I\n" +
	"\x11GetSymbolResponse\x124\n" +
	"\x06symbol\x18\x01 \x01(\v2\x12.symbols.v1.SymbolB\b\xfaB\x05\x8a\x01\x02\x10\x01R\x06symbol\"\xc7\x03\n" +
	"\x12ListSymbolsRequest\x12&\n" +
	"\n" +
	"project_id\x18\x01 \x01(\x05B\a\xfaB\x04\x1a\x02 \x00R\tprojectId\x12&\n" +
	"\tpage_size\x18\x02 \x01(\x05B\t\xfaB\x06\x1a\x04\x18d(\x01R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\x12A\n" +
	"\border_by\x18\x04 \x01(\x0e2&.symbols.v1.ListSymbolsRequest.OrderByR\aorderBy\x12S\n" +
	"\x0esort_direction\x18\x05 \x01(\x0e2,.symbols.v1.ListSymbolsRequest.SortDirectionR\rsortDirection\"H\n" +
	"\aOrderBy\x12\x18\n" +
	"\x14ORDER_BY_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vORDER_BY_ID\x10\x01\x12\x12\n" +
	"\x0eORDER_BY_LABEL\x10\x03\"`\n" +
	"\rSortDirection\x12\x1e\n" +
	"\x1aSORT_DIRECTION_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12SORT_DIRECTION_ASC\x10\x01\x12\x17\n" +
	"\x13SORT_DIRECTION_DESC\x10\x02\"\x7f\n" +
	"\x13ListSymbolsResponse\x12,\n" +
	"\asymbols\x18\x01 \x03(\v2\x12.symbols.v1.SymbolR\asymbols\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\x12\x1b\n" +
	"\tnext_page\x18\x03 \x01(\x05R\bnextPage2\xb0\x04\n" +
	"\aSymbols\x12i\n" +
	"\fCreateSymbol\x12\x1f.symbols.v1.CreateSymbolRequest\x1a .symbols.v1.CreateSymbolResponse\"\x16\x82\xd3\xe4\x93\x02\x10:\x01*\"\v/v1/symbols\x12b\n" +
	"\tGetSymbol\x12\x1c.symbols.v1.GetSymbolRequest\x1a\x1d.symbols.v1.GetSymbolResponse\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/v1/symbols/{id}\x12n\n" +
	"\fUpdateSymbol\x12\x1f.symbols.v1.UpdateSymbolRequest\x1a .symbols.v1.UpdateSymbolResponse\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\x1a\x10/v1/symbols/{id}\x12k\n" +
	"\fDeleteSymbol\x12\x1f.symbols.v1.DeleteSymbolRequest\x1a .symbols.v1.DeleteSymbolResponse\"\x18\x82\xd3\xe4\x93\x02\x12*\x10/v1/symbols/{id}\x12y\n" +
	"\vListSymbols\x12\x1e.symbols.v1.ListSymbolsRequest\x1a\x1f.symbols.v1.ListSymbolsResponse\")\x82\xd3\xe4\x93\x02#\x12!/v1/projects/{project_id}/symbolsBO\n" +
	"\x19dev.kratos.api.symbols.v1B\x0eSymbolsProtoV1P\x01Z symbol-service/api/symbols/v1;v1b\x06proto3"

var (
	file_symbol_v1_symbols_proto_rawDescOnce sync.Once
	file_symbol_v1_symbols_proto_rawDescData []byte
)

func file_symbol_v1_symbols_proto_rawDescGZIP() []byte {
	file_symbol_v1_symbols_proto_rawDescOnce.Do(func() {
		file_symbol_v1_symbols_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_symbol_v1_symbols_proto_rawDesc), len(file_symbol_v1_symbols_proto_rawDesc)))
	})
	return file_symbol_v1_symbols_proto_rawDescData
}

var file_symbol_v1_symbols_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_symbol_v1_symbols_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_symbol_v1_symbols_proto_goTypes = []any{
	(ListSymbolsRequest_OrderBy)(0),       // 0: symbols.v1.ListSymbolsRequest.OrderBy
	(ListSymbolsRequest_SortDirection)(0), // 1: symbols.v1.ListSymbolsRequest.SortDirection
	(*Symbol)(nil),                        // 2: symbols.v1.Symbol
	(*CreateSymbolRequest)(nil),           // 3: symbols.v1.CreateSymbolRequest
	(*CreateSymbolResponse)(nil),          // 4: symbols.v1.CreateSymbolResponse
	(*UpdateSymbolRequest)(nil),           // 5: symbols.v1.UpdateSymbolRequest
	(*UpdateSymbolResponse)(nil),          // 6: symbols.v1.UpdateSymbolResponse
	(*DeleteSymbolRequest)(nil),           // 7: symbols.v1.DeleteSymbolRequest
	(*DeleteSymbolResponse)(nil),          // 8: symbols.v1.DeleteSymbolResponse
	(*GetSymbolRequest)(nil),              // 9: symbols.v1.GetSymbolRequest
	(*GetSymbolResponse)(nil),             // 10: symbols.v1.GetSymbolResponse
	(*ListSymbolsRequest)(nil),            // 11: symbols.v1.ListSymbolsRequest
	(*ListSymbolsResponse)(nil),           // 12: symbols.v1.ListSymbolsResponse
	(*wrapperspb.Int32Value)(nil),         // 13: google.protobuf.Int32Value
	(*wrapperspb.StringValue)(nil),        // 14: google.protobuf.StringValue
	(*wrapperspb.BytesValue)(nil),         // 15: google.protobuf.BytesValue
}
var file_symbol_v1_symbols_proto_depIdxs = []int32{
	2,  // 0: symbols.v1.CreateSymbolResponse.symbol:type_name -> symbols.v1.Symbol
	13, // 1: symbols.v1.UpdateSymbolRequest.project_id:type_name -> google.protobuf.Int32Value
	14, // 2: symbols.v1.UpdateSymbolRequest.uid:type_name -> google.protobuf.StringValue
	14, // 3: symbols.v1.UpdateSymbolRequest.label:type_name -> google.protobuf.StringValue
	14, // 4: symbols.v1.UpdateSymbolRequest.class_name:type_name -> google.protobuf.StringValue
	14, // 5: symbols.v1.UpdateSymbolRequest.component_target:type_name -> google.protobuf.StringValue
	14, // 6: symbols.v1.UpdateSymbolRequest.version:type_name -> google.protobuf.StringValue
	15, // 7: symbols.v1.UpdateSymbolRequest.data:type_name -> google.protobuf.BytesValue
	2,  // 8: symbols.v1.UpdateSymbolResponse.symbol:type_name -> symbols.v1.Symbol
	2,  // 9: symbols.v1.GetSymbolResponse.symbol:type_name -> symbols.v1.Symbol
	0,  // 10: symbols.v1.ListSymbolsRequest.order_by:type_name -> symbols.v1.ListSymbolsRequest.OrderBy
	1,  // 11: symbols.v1.ListSymbolsRequest.sort_direction:type_name -> symbols.v1.ListSymbolsRequest.SortDirection
	2,  // 12: symbols.v1.ListSymbolsResponse.symbols:type_name -> symbols.v1.Symbol
	3,  // 13: symbols.v1.Symbols.CreateSymbol:input_type -> symbols.v1.CreateSymbolRequest
	9,  // 14: symbols.v1.Symbols.GetSymbol:input_type -> symbols.v1.GetSymbolRequest
	5,  // 15: symbols.v1.Symbols.UpdateSymbol:input_type -> symbols.v1.UpdateSymbolRequest
	7,  // 16: symbols.v1.Symbols.DeleteSymbol:input_type -> symbols.v1.DeleteSymbolRequest
	11, // 17: symbols.v1.Symbols.ListSymbols:input_type -> symbols.v1.ListSymbolsRequest
	4,  // 18: symbols.v1.Symbols.CreateSymbol:output_type -> symbols.v1.CreateSymbolResponse
	10, // 19: symbols.v1.Symbols.GetSymbol:output_type -> symbols.v1.GetSymbolResponse
	6,  // 20: symbols.v1.Symbols.UpdateSymbol:output_type -> symbols.v1.UpdateSymbolResponse
	8,  // 21: symbols.v1.Symbols.DeleteSymbol:output_type -> symbols.v1.DeleteSymbolResponse
	12, // 22: symbols.v1.Symbols.ListSymbols:output_type -> symbols.v1.ListSymbolsResponse
	18, // [18:23] is the sub-list for method output_type
	13, // [13:18] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_symbol_v1_symbols_proto_init() }
func file_symbol_v1_symbols_proto_init() {
	if File_symbol_v1_symbols_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_symbol_v1_symbols_proto_rawDesc), len(file_symbol_v1_symbols_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_symbol_v1_symbols_proto_goTypes,
		DependencyIndexes: file_symbol_v1_symbols_proto_depIdxs,
		EnumInfos:         file_symbol_v1_symbols_proto_enumTypes,
		MessageInfos:      file_symbol_v1_symbols_proto_msgTypes,
	}.Build()
	File_symbol_v1_symbols_proto = out.File
	file_symbol_v1_symbols_proto_goTypes = nil
	file_symbol_v1_symbols_proto_depIdxs = nil
}
