// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: symbol/v1/symbols.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Symbols_CreateSymbol_FullMethodName = "/symbols.v1.Symbols/CreateSymbol"
	Symbols_GetSymbol_FullMethodName    = "/symbols.v1.Symbols/GetSymbol"
	Symbols_UpdateSymbol_FullMethodName = "/symbols.v1.Symbols/UpdateSymbol"
	Symbols_DeleteSymbol_FullMethodName = "/symbols.v1.Symbols/DeleteSymbol"
	Symbols_ListSymbols_FullMethodName  = "/symbols.v1.Symbols/ListSymbols"
)

// SymbolsClient is the client API for Symbols service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The greeting service definition.
type SymbolsClient interface {
	// Sends a greeting
	CreateSymbol(ctx context.Context, in *CreateSymbolRequest, opts ...grpc.CallOption) (*CreateSymbolResponse, error)
	GetSymbol(ctx context.Context, in *GetSymbolRequest, opts ...grpc.CallOption) (*GetSymbolResponse, error)
	UpdateSymbol(ctx context.Context, in *UpdateSymbolRequest, opts ...grpc.CallOption) (*UpdateSymbolResponse, error)
	DeleteSymbol(ctx context.Context, in *DeleteSymbolRequest, opts ...grpc.CallOption) (*DeleteSymbolResponse, error)
	ListSymbols(ctx context.Context, in *ListSymbolsRequest, opts ...grpc.CallOption) (*ListSymbolsResponse, error)
}

type symbolsClient struct {
	cc grpc.ClientConnInterface
}

func NewSymbolsClient(cc grpc.ClientConnInterface) SymbolsClient {
	return &symbolsClient{cc}
}

func (c *symbolsClient) CreateSymbol(ctx context.Context, in *CreateSymbolRequest, opts ...grpc.CallOption) (*CreateSymbolResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateSymbolResponse)
	err := c.cc.Invoke(ctx, Symbols_CreateSymbol_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *symbolsClient) GetSymbol(ctx context.Context, in *GetSymbolRequest, opts ...grpc.CallOption) (*GetSymbolResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSymbolResponse)
	err := c.cc.Invoke(ctx, Symbols_GetSymbol_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *symbolsClient) UpdateSymbol(ctx context.Context, in *UpdateSymbolRequest, opts ...grpc.CallOption) (*UpdateSymbolResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateSymbolResponse)
	err := c.cc.Invoke(ctx, Symbols_UpdateSymbol_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *symbolsClient) DeleteSymbol(ctx context.Context, in *DeleteSymbolRequest, opts ...grpc.CallOption) (*DeleteSymbolResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteSymbolResponse)
	err := c.cc.Invoke(ctx, Symbols_DeleteSymbol_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *symbolsClient) ListSymbols(ctx context.Context, in *ListSymbolsRequest, opts ...grpc.CallOption) (*ListSymbolsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSymbolsResponse)
	err := c.cc.Invoke(ctx, Symbols_ListSymbols_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SymbolsServer is the server API for Symbols service.
// All implementations must embed UnimplementedSymbolsServer
// for forward compatibility.
//
// The greeting service definition.
type SymbolsServer interface {
	// Sends a greeting
	CreateSymbol(context.Context, *CreateSymbolRequest) (*CreateSymbolResponse, error)
	GetSymbol(context.Context, *GetSymbolRequest) (*GetSymbolResponse, error)
	UpdateSymbol(context.Context, *UpdateSymbolRequest) (*UpdateSymbolResponse, error)
	DeleteSymbol(context.Context, *DeleteSymbolRequest) (*DeleteSymbolResponse, error)
	ListSymbols(context.Context, *ListSymbolsRequest) (*ListSymbolsResponse, error)
	mustEmbedUnimplementedSymbolsServer()
}

// UnimplementedSymbolsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSymbolsServer struct{}

func (UnimplementedSymbolsServer) CreateSymbol(context.Context, *CreateSymbolRequest) (*CreateSymbolResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSymbol not implemented")
}
func (UnimplementedSymbolsServer) GetSymbol(context.Context, *GetSymbolRequest) (*GetSymbolResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSymbol not implemented")
}
func (UnimplementedSymbolsServer) UpdateSymbol(context.Context, *UpdateSymbolRequest) (*UpdateSymbolResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateSymbol not implemented")
}
func (UnimplementedSymbolsServer) DeleteSymbol(context.Context, *DeleteSymbolRequest) (*DeleteSymbolResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteSymbol not implemented")
}
func (UnimplementedSymbolsServer) ListSymbols(context.Context, *ListSymbolsRequest) (*ListSymbolsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListSymbols not implemented")
}
func (UnimplementedSymbolsServer) mustEmbedUnimplementedSymbolsServer() {}
func (UnimplementedSymbolsServer) testEmbeddedByValue()                 {}

// UnsafeSymbolsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SymbolsServer will
// result in compilation errors.
type UnsafeSymbolsServer interface {
	mustEmbedUnimplementedSymbolsServer()
}

func RegisterSymbolsServer(s grpc.ServiceRegistrar, srv SymbolsServer) {
	// If the following call pancis, it indicates UnimplementedSymbolsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Symbols_ServiceDesc, srv)
}

func _Symbols_CreateSymbol_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSymbolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SymbolsServer).CreateSymbol(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Symbols_CreateSymbol_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SymbolsServer).CreateSymbol(ctx, req.(*CreateSymbolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Symbols_GetSymbol_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSymbolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SymbolsServer).GetSymbol(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Symbols_GetSymbol_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SymbolsServer).GetSymbol(ctx, req.(*GetSymbolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Symbols_UpdateSymbol_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSymbolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SymbolsServer).UpdateSymbol(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Symbols_UpdateSymbol_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SymbolsServer).UpdateSymbol(ctx, req.(*UpdateSymbolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Symbols_DeleteSymbol_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSymbolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SymbolsServer).DeleteSymbol(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Symbols_DeleteSymbol_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SymbolsServer).DeleteSymbol(ctx, req.(*DeleteSymbolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Symbols_ListSymbols_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSymbolsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SymbolsServer).ListSymbols(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Symbols_ListSymbols_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SymbolsServer).ListSymbols(ctx, req.(*ListSymbolsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Symbols_ServiceDesc is the grpc.ServiceDesc for Symbols service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Symbols_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "symbols.v1.Symbols",
	HandlerType: (*SymbolsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSymbol",
			Handler:    _Symbols_CreateSymbol_Handler,
		},
		{
			MethodName: "GetSymbol",
			Handler:    _Symbols_GetSymbol_Handler,
		},
		{
			MethodName: "UpdateSymbol",
			Handler:    _Symbols_UpdateSymbol_Handler,
		},
		{
			MethodName: "DeleteSymbol",
			Handler:    _Symbols_DeleteSymbol_Handler,
		},
		{
			MethodName: "ListSymbols",
			Handler:    _Symbols_ListSymbols_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "symbol/v1/symbols.proto",
}
