api:
  insecure: true
  dashboard: false

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false

entryPoints:
  web:
    address: ":80"
    forwardedHeaders:
      insecure: true

log:
  level: ERROR