name: Service Testing

on:
  push:
    branches:
      - main
  pull_request:
    branches: ['**']
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read

env:
  GO_VERSION: '1.25'

jobs:
  detect-services:
    name: Detect Services
    runs-on: ubuntu-latest
    timeout-minutes: 5
    outputs:
      services: ${{ steps.set-services.outputs.services }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Detect service directories
        id: set-services
        run: |
          # Find all service directories
          services=$(ls -d services/*/ 2>/dev/null | xargs -n 1 basename | jq -R -s -c 'split("\n")[:-1]')
          echo "services=$services" >> $GITHUB_OUTPUT
          echo "Detected services: $services"

  test:
    name: Test ${{ matrix.service }}
    runs-on: ubuntu-latest
    timeout-minutes: 15
    needs: [detect-services]

    strategy:
      fail-fast: false
      matrix:
        service: ${{ fromJSON(needs.detect-services.outputs.services) }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true
          cache-dependency-path: |
            go.work.sum
            services/${{ matrix.service }}/go.sum
            platform/go.sum
            contracts/go.sum

      - name: Cache Go build cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-build-${{ matrix.service }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-build-${{ matrix.service }}-
            ${{ runner.os }}-go-build-

      - name: Download Go modules
        working-directory: services/${{ matrix.service }}
        run: |
          # Download dependencies for workspace
          go mod download

      - name: Run tests with race detection
        working-directory: services/${{ matrix.service }}
        run: |
          # Run unit tests with race detector and coverage
          make test

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ matrix.service }}
          path: services/${{ matrix.service }}/coverage.out
          retention-days: 7
          if-no-files-found: error

      - name: Display coverage summary
        working-directory: services/${{ matrix.service }}
        run: |
          # Show coverage percentage in logs
          echo "Coverage for ${{ matrix.service }}:"
          go tool cover -func=coverage.out | tail -n 1
