// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: symbols/v1/symbols.proto

package v1connect

import (
	connect "connectrpc.com/connect"
	v1 "contacts/symbols/v1"
	context "context"
	errors "errors"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// SymbolsServiceName is the fully-qualified name of the SymbolsService service.
	SymbolsServiceName = "symbols.v1.SymbolsService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// SymbolsServiceCreateSymbolProcedure is the fully-qualified name of the SymbolsService's
	// CreateSymbol RPC.
	SymbolsServiceCreateSymbolProcedure = "/symbols.v1.SymbolsService/CreateSymbol"
	// SymbolsServiceGetSymbolProcedure is the fully-qualified name of the SymbolsService's GetSymbol
	// RPC.
	SymbolsServiceGetSymbolProcedure = "/symbols.v1.SymbolsService/GetSymbol"
	// SymbolsServiceUpdateSymbolProcedure is the fully-qualified name of the SymbolsService's
	// UpdateSymbol RPC.
	SymbolsServiceUpdateSymbolProcedure = "/symbols.v1.SymbolsService/UpdateSymbol"
	// SymbolsServiceDeleteSymbolProcedure is the fully-qualified name of the SymbolsService's
	// DeleteSymbol RPC.
	SymbolsServiceDeleteSymbolProcedure = "/symbols.v1.SymbolsService/DeleteSymbol"
	// SymbolsServiceListSymbolsProcedure is the fully-qualified name of the SymbolsService's
	// ListSymbols RPC.
	SymbolsServiceListSymbolsProcedure = "/symbols.v1.SymbolsService/ListSymbols"
)

// SymbolsServiceClient is a client for the symbols.v1.SymbolsService service.
type SymbolsServiceClient interface {
	// Sends a greeting
	CreateSymbol(context.Context, *v1.CreateSymbolRequest) (*v1.CreateSymbolResponse, error)
	GetSymbol(context.Context, *v1.GetSymbolRequest) (*v1.GetSymbolResponse, error)
	UpdateSymbol(context.Context, *v1.UpdateSymbolRequest) (*v1.UpdateSymbolResponse, error)
	DeleteSymbol(context.Context, *v1.DeleteSymbolRequest) (*v1.DeleteSymbolResponse, error)
	ListSymbols(context.Context, *v1.ListSymbolsRequest) (*v1.ListSymbolsResponse, error)
}

// NewSymbolsServiceClient constructs a client for the symbols.v1.SymbolsService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewSymbolsServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) SymbolsServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	symbolsServiceMethods := v1.File_symbols_v1_symbols_proto.Services().ByName("SymbolsService").Methods()
	return &symbolsServiceClient{
		createSymbol: connect.NewClient[v1.CreateSymbolRequest, v1.CreateSymbolResponse](
			httpClient,
			baseURL+SymbolsServiceCreateSymbolProcedure,
			connect.WithSchema(symbolsServiceMethods.ByName("CreateSymbol")),
			connect.WithClientOptions(opts...),
		),
		getSymbol: connect.NewClient[v1.GetSymbolRequest, v1.GetSymbolResponse](
			httpClient,
			baseURL+SymbolsServiceGetSymbolProcedure,
			connect.WithSchema(symbolsServiceMethods.ByName("GetSymbol")),
			connect.WithClientOptions(opts...),
		),
		updateSymbol: connect.NewClient[v1.UpdateSymbolRequest, v1.UpdateSymbolResponse](
			httpClient,
			baseURL+SymbolsServiceUpdateSymbolProcedure,
			connect.WithSchema(symbolsServiceMethods.ByName("UpdateSymbol")),
			connect.WithClientOptions(opts...),
		),
		deleteSymbol: connect.NewClient[v1.DeleteSymbolRequest, v1.DeleteSymbolResponse](
			httpClient,
			baseURL+SymbolsServiceDeleteSymbolProcedure,
			connect.WithSchema(symbolsServiceMethods.ByName("DeleteSymbol")),
			connect.WithClientOptions(opts...),
		),
		listSymbols: connect.NewClient[v1.ListSymbolsRequest, v1.ListSymbolsResponse](
			httpClient,
			baseURL+SymbolsServiceListSymbolsProcedure,
			connect.WithSchema(symbolsServiceMethods.ByName("ListSymbols")),
			connect.WithClientOptions(opts...),
		),
	}
}

// symbolsServiceClient implements SymbolsServiceClient.
type symbolsServiceClient struct {
	createSymbol *connect.Client[v1.CreateSymbolRequest, v1.CreateSymbolResponse]
	getSymbol    *connect.Client[v1.GetSymbolRequest, v1.GetSymbolResponse]
	updateSymbol *connect.Client[v1.UpdateSymbolRequest, v1.UpdateSymbolResponse]
	deleteSymbol *connect.Client[v1.DeleteSymbolRequest, v1.DeleteSymbolResponse]
	listSymbols  *connect.Client[v1.ListSymbolsRequest, v1.ListSymbolsResponse]
}

// CreateSymbol calls symbols.v1.SymbolsService.CreateSymbol.
func (c *symbolsServiceClient) CreateSymbol(ctx context.Context, req *v1.CreateSymbolRequest) (*v1.CreateSymbolResponse, error) {
	response, err := c.createSymbol.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// GetSymbol calls symbols.v1.SymbolsService.GetSymbol.
func (c *symbolsServiceClient) GetSymbol(ctx context.Context, req *v1.GetSymbolRequest) (*v1.GetSymbolResponse, error) {
	response, err := c.getSymbol.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// UpdateSymbol calls symbols.v1.SymbolsService.UpdateSymbol.
func (c *symbolsServiceClient) UpdateSymbol(ctx context.Context, req *v1.UpdateSymbolRequest) (*v1.UpdateSymbolResponse, error) {
	response, err := c.updateSymbol.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// DeleteSymbol calls symbols.v1.SymbolsService.DeleteSymbol.
func (c *symbolsServiceClient) DeleteSymbol(ctx context.Context, req *v1.DeleteSymbolRequest) (*v1.DeleteSymbolResponse, error) {
	response, err := c.deleteSymbol.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// ListSymbols calls symbols.v1.SymbolsService.ListSymbols.
func (c *symbolsServiceClient) ListSymbols(ctx context.Context, req *v1.ListSymbolsRequest) (*v1.ListSymbolsResponse, error) {
	response, err := c.listSymbols.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// SymbolsServiceHandler is an implementation of the symbols.v1.SymbolsService service.
type SymbolsServiceHandler interface {
	// Sends a greeting
	CreateSymbol(context.Context, *v1.CreateSymbolRequest) (*v1.CreateSymbolResponse, error)
	GetSymbol(context.Context, *v1.GetSymbolRequest) (*v1.GetSymbolResponse, error)
	UpdateSymbol(context.Context, *v1.UpdateSymbolRequest) (*v1.UpdateSymbolResponse, error)
	DeleteSymbol(context.Context, *v1.DeleteSymbolRequest) (*v1.DeleteSymbolResponse, error)
	ListSymbols(context.Context, *v1.ListSymbolsRequest) (*v1.ListSymbolsResponse, error)
}

// NewSymbolsServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewSymbolsServiceHandler(svc SymbolsServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	symbolsServiceMethods := v1.File_symbols_v1_symbols_proto.Services().ByName("SymbolsService").Methods()
	symbolsServiceCreateSymbolHandler := connect.NewUnaryHandlerSimple(
		SymbolsServiceCreateSymbolProcedure,
		svc.CreateSymbol,
		connect.WithSchema(symbolsServiceMethods.ByName("CreateSymbol")),
		connect.WithHandlerOptions(opts...),
	)
	symbolsServiceGetSymbolHandler := connect.NewUnaryHandlerSimple(
		SymbolsServiceGetSymbolProcedure,
		svc.GetSymbol,
		connect.WithSchema(symbolsServiceMethods.ByName("GetSymbol")),
		connect.WithHandlerOptions(opts...),
	)
	symbolsServiceUpdateSymbolHandler := connect.NewUnaryHandlerSimple(
		SymbolsServiceUpdateSymbolProcedure,
		svc.UpdateSymbol,
		connect.WithSchema(symbolsServiceMethods.ByName("UpdateSymbol")),
		connect.WithHandlerOptions(opts...),
	)
	symbolsServiceDeleteSymbolHandler := connect.NewUnaryHandlerSimple(
		SymbolsServiceDeleteSymbolProcedure,
		svc.DeleteSymbol,
		connect.WithSchema(symbolsServiceMethods.ByName("DeleteSymbol")),
		connect.WithHandlerOptions(opts...),
	)
	symbolsServiceListSymbolsHandler := connect.NewUnaryHandlerSimple(
		SymbolsServiceListSymbolsProcedure,
		svc.ListSymbols,
		connect.WithSchema(symbolsServiceMethods.ByName("ListSymbols")),
		connect.WithHandlerOptions(opts...),
	)
	return "/symbols.v1.SymbolsService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case SymbolsServiceCreateSymbolProcedure:
			symbolsServiceCreateSymbolHandler.ServeHTTP(w, r)
		case SymbolsServiceGetSymbolProcedure:
			symbolsServiceGetSymbolHandler.ServeHTTP(w, r)
		case SymbolsServiceUpdateSymbolProcedure:
			symbolsServiceUpdateSymbolHandler.ServeHTTP(w, r)
		case SymbolsServiceDeleteSymbolProcedure:
			symbolsServiceDeleteSymbolHandler.ServeHTTP(w, r)
		case SymbolsServiceListSymbolsProcedure:
			symbolsServiceListSymbolsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedSymbolsServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedSymbolsServiceHandler struct{}

func (UnimplementedSymbolsServiceHandler) CreateSymbol(context.Context, *v1.CreateSymbolRequest) (*v1.CreateSymbolResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("symbols.v1.SymbolsService.CreateSymbol is not implemented"))
}

func (UnimplementedSymbolsServiceHandler) GetSymbol(context.Context, *v1.GetSymbolRequest) (*v1.GetSymbolResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("symbols.v1.SymbolsService.GetSymbol is not implemented"))
}

func (UnimplementedSymbolsServiceHandler) UpdateSymbol(context.Context, *v1.UpdateSymbolRequest) (*v1.UpdateSymbolResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("symbols.v1.SymbolsService.UpdateSymbol is not implemented"))
}

func (UnimplementedSymbolsServiceHandler) DeleteSymbol(context.Context, *v1.DeleteSymbolRequest) (*v1.DeleteSymbolResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("symbols.v1.SymbolsService.DeleteSymbol is not implemented"))
}

func (UnimplementedSymbolsServiceHandler) ListSymbols(context.Context, *v1.ListSymbolsRequest) (*v1.ListSymbolsResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("symbols.v1.SymbolsService.ListSymbols is not implemented"))
}
