// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"platform/logger"
	"platform/metrics"
	"symbols/internal/biz"
	"symbols/internal/conf/gen"
	"symbols/internal/data"
	"symbols/internal/data/repo"
	"symbols/internal/handlers"
	"symbols/internal/worker"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(server *conf.Server, confData *conf.Data, logConfig *conf.LogConfig, metrics *conf.Metrics, logLogger log.Logger) (*kratos.App, func(), error) {
	db := data.NewDB(confData, logLogger)
	dataData, cleanup, err := data.NewData(db, logLogger)
	if err != nil {
		return nil, nil, err
	}
	transaction := data.NewTransaction(dataData)
	symbolRepo := repo.NewSymbolRepo(db, transaction, logLogger)
	validate := biz.NewSymbolValidator()
	watermillLogger := logger.NewWatermillLogger(logLogger)
	publisher := data.NewAmqpPublisher(confData, logLogger, watermillLogger)
	registry := NewWorkerMetricsRegistry(metrics)
	eventsPublisher := data.NewEventPublisherWithMetrics(publisher, metrics, registry, logLogger)
	symbolUseCase := biz.NewSymbolUseCase(symbolRepo, validate, transaction, eventsPublisher, logLogger)
	lifecycleEventHandler := handlers.NewLifecycleEventHandler(symbolUseCase, logLogger)
	subscriber := data.NewAmqpSubscriber(confData, logLogger, watermillLogger)
	eventsSubscriber := data.NewEventSubscriberWithMetrics(subscriber, metrics, registry, logLogger)
	router := worker.NewRouter(confData, lifecycleEventHandler, eventsPublisher, eventsSubscriber, watermillLogger)
	workerWorker := worker.NewWorker(router, logLogger)
	app := newApp(workerWorker, logLogger)
	return app, func() {
		cleanup()
	}, nil
}

// wire.go:

// NewWorkerMetricsRegistry creates a metrics registry for the worker (returns nil for MVP).
func NewWorkerMetricsRegistry(mc *conf.Metrics) *metrics.Registry {

	return nil
}
