// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"symbols/internal/conf/gen"
	"symbols/internal/worker"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(server *conf.Server, data *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	router := worker.NewRouter(logger)
	workerWorker := worker.NewWorker(router, logger)
	app := newApp(workerWorker, logger)
	return app, func() {
	}, nil
}
