// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"platform/logger"
	"symbols/internal/biz"
	"symbols/internal/conf/gen"
	"symbols/internal/data"
	"symbols/internal/data/mq"
	"symbols/internal/data/repo"
	"symbols/internal/server"
	"symbols/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logConfig *conf.LogConfig, logLogger log.Logger) (*kratos.App, func(), error) {
	db := data.NewDB(confData, logLogger)
	dataData, cleanup, err := data.NewData(db, logLogger)
	if err != nil {
		return nil, nil, err
	}
	transaction := data.NewTransaction(dataData)
	symbolRepo := repo.NewSymbolRepo(db, transaction, logLogger)
	validate := biz.NewSymbolValidator()
	watermillLogger := logger.NewWatermillLogger(logLogger)
	publisher := data.NewAmqpPublisher(confData, logLogger, watermillLogger)
	eventsPublisher := mq.NewEventPublisher(publisher, logLogger)
	symbolUseCase := biz.NewSymbolUseCase(symbolRepo, validate, transaction, eventsPublisher, logLogger)
	symbolService := service.NewSymbolService(symbolUseCase)
	grpcServer := server.NewGRPCServer(confServer, symbolService, logLogger)
	httpServer := server.NewHTTPServer(confServer, symbolService, logLogger)
	app := newApp(logLogger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
