// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"platform/build"
	"platform/logger"
	"symbols/internal/biz/symbol"
	"symbols/internal/conf/gen"
	"symbols/internal/data"
	"symbols/internal/data/repo"
	"symbols/internal/server"
	"symbols/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(serviceBuildInfo *build.ServiceBuildInfo, confServer *conf.Server, confData *conf.Data, logConfig *conf.LogConfig, metrics *conf.Metrics, logLogger log.Logger) (*kratos.App, func(), error) {
	registry := server.NewMetricsRegistry(metrics, serviceBuildInfo)
	db := data.NewDB(confData, logLogger)
	dataData, cleanup, err := data.NewData(db, logLogger)
	if err != nil {
		return nil, nil, err
	}
	transaction := data.NewTransaction(dataData)
	symbolRepo := repo.NewSymbolRepo(db, transaction, logLogger)
	validate := symbol.NewValidator()
	watermillLogger := logger.NewWatermillLogger(logLogger)
	publisher := data.NewAMQPPublisher(confData, logLogger, watermillLogger)
	symbolEventPublisher := data.NewEventPublisherWithMetrics(publisher, metrics, registry, logLogger)
	symbolUseCase := symbol.NewUseCase(symbolRepo, validate, transaction, symbolEventPublisher, logLogger)
	symbolService := service.NewSymbolService(symbolUseCase)
	grpcServer := server.NewGRPCServer(confServer, metrics, registry, symbolService, logLogger)
	httpServer := server.NewHTTPServer(confServer, metrics, registry, symbolService, logLogger)
	app := newApp(logLogger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
