// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"symbols/internal/biz"
	"symbols/internal/conf/gen"
	"symbols/internal/data"
	"symbols/internal/data/mq"
	"symbols/internal/data/repo"
	"symbols/internal/server"
	"symbols/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	db := data.NewDB(confData, logger)
	dataData, cleanup, err := data.NewData(db, logger)
	if err != nil {
		return nil, nil, err
	}
	transaction := data.NewTransaction(dataData)
	symbolRepo := repo.NewSymbolRepo(db, transaction, logger)
	validate := biz.NewSymbolValidator()
	publisher := data.NewAmqpPublisher(confData, logger)
	eventPublisher := mq.NewEventPublisher(publisher)
	symbolUseCase := biz.NewSymbolUseCase(symbolRepo, validate, transaction, eventPublisher, logger)
	symbolService := service.NewSymbolService(symbolUseCase)
	grpcServer := server.NewGRPCServer(confServer, symbolService, logger)
	httpServer := server.NewHTTPServer(confServer, symbolService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
